name: Make Build Check # ワークフローの名前

on:
  push:
    branches: [ main, master, tkatsuma_readline_test ]
  pull_request:
    branches: [ main, master ]

jobs:
  build: # ジョブの名前
    runs-on: ubuntu-22.04 # 実行環境 (Linuxの最新版を使用)

    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 必要なコンパイラやツールをインストール (C/C++の場合の例)
      # makeが使用する言語やツールに応じて、このステップを追加・変更します
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libbsd-dev libreadline-dev 

      # 3. makeコマンドを実行してビルド
      - name: Run make
        run: make # リポジトリのルートにあるMakefileが実行されます
        # 特定のターゲットを指定する場合は `run: make <ターゲット名>` に変更